{% set name = "elfutils" %}
{% set version = "0.183" %}
{% set sha256 = "c3637c208d309d58714a51e61e63f1958808fead882e9b607506a29e5474f2c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://fedorahosted.org/releases/e/l/elfutils/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('elfutils', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - make
    - pkg-config
  host:
    - bzip2
    - libarchive
    - libcurl
    - libmicrohttpd
    - m4
    - sqlite
    - xz
    - zlib
    - zstd


test:
  requires:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
    - pkg-config

about:
  home: https://fedorahosted.org/elfutils/
  license: LGPL-3.0-only
  license_file: COPYING-LGPLV3
  summary: a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.

extra:
  recipe-maintainers:
    - edisongustavo
    - xhochy
