{% set version = "0.186" %}

package:
  name: elfutils
  version: {{ version }}

source:
  fn: elfutils-{{ version }}.tar.bz2
  url: https://fedorahosted.org/releases/e/l/elfutils/{{ version }}/elfutils-{{ version }}.tar.bz2
  sha256: 7f6fb9149b1673d38d9178a0d3e0fb8a1ec4f53a9f4c2ff89469609879641177
  patches:
    - patches/0001-rm-test-nlist-too-fragile.patch
    - patches/0002-check-for-cap_sys_ptrace-when-needed-or-skip.patch

build:
  number: 1
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('elfutils', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
    - autoconf
    - automake
    - libtool
  host:
    - bzip2
    - libarchive
    - libcurl
    - libmicrohttpd
    - m4
    - sqlite
    - xz
    - zlib
    - zstd

test:
  requires:
    - {{ compiler('c') }}
    - pkg-config

about:
  home: https://fedorahosted.org/elfutils/
  license: LGPL-3.0-only
  license_file: COPYING-LGPLV3
  summary: a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.

extra:
  recipe-maintainers:
    - edisongustavo
    - xhochy
