{% set version = "0.192" %}

package:
  name: elfutils
  version: {{ version }}

source:
  fn: elfutils-{{ version }}.tar.bz2
  url: https://fedorahosted.org/releases/e/l/elfutils/{{ version }}/elfutils-{{ version }}.tar.bz2
  sha256: 616099beae24aba11f9b63d86ca6cc8d566d968b802391334c91df54eab416b4

build:
  number: 2
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('elfutils', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - bzip2
    - libarchive
    - libcurl
    - libmicrohttpd
    - m4
    - sqlite
    - liblzma-devel
    - zlib
    - zstd

test:
  requires:
    - {{ compiler('c') }}
    - pkg-config

about:
  home: https://fedorahosted.org/elfutils/
  license: LGPL-3.0-only
  license_file: COPYING-LGPLV3
  summary: a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.

extra:
  recipe-maintainers:
    - edisongustavo
    - xhochy
