{% set name = "elfutils" %}
{% set version = "0.182" %}
{% set sha256 = "ecc406914edf335f0b7fc084ebe6c460c4d6d5175bfdd6688c1c78d9146b8858" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://fedorahosted.org/releases/e/l/elfutils/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('elfutils', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - bzip2
    - libarchive
    - libcurl
    - libmicrohttpd
    - m4
    - sqlite
    - xz
    - zlib
    - zstd


test:
  requires:
    - {{ compiler('c') }}
    - pkg-config

about:
  home: https://fedorahosted.org/elfutils/
  license: LGPL-3.0-only
  license_file: COPYING-LGPLV3
  summary: a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.

extra:
  recipe-maintainers:
    - edisongustavo
    - xhochy
