{% set version = "0.191" %}

package:
  name: elfutils
  version: {{ version }}

source:
  fn: elfutils-{{ version }}.tar.bz2
  url: https://fedorahosted.org/releases/e/l/elfutils/{{ version }}/elfutils-{{ version }}.tar.bz2
  sha256: df76db71366d1d708365fc7a6c60ca48398f14367eb2b8954efc8897147ad871

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('elfutils', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - bzip2
    - libarchive
    - libcurl
    - libmicrohttpd
    - m4
    - sqlite
    - xz
    - zlib
    - zstd

test:
  requires:
    - {{ compiler('c') }}
    - pkg-config

about:
  home: https://fedorahosted.org/elfutils/
  license: LGPL-3.0-only
  license_file: COPYING-LGPLV3
  summary: a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.

extra:
  recipe-maintainers:
    - edisongustavo
    - xhochy
