{% set name = "elfutils" %}
{% set version = "0.172" %}
{% set sha256 = "779c99e6344c4982bbab60b8d276cec3d468151c758905f9a44ba6b6edaa0e24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://fedorahosted.org/releases/e/l/elfutils/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - toolchain
    - zlib 1.2.*
    - m4

  run:
    - zlib 1.2.*

about:
  home: https://fedorahosted.org/elfutils/
  license: LGPL-3.0
  summary: 'a set of utilities and libraries for handling ELF (Executable and Linkable Format) files.'

extra:
  recipe-maintainers:
    - edisongustavo
