travis:
  secure:
    BINSTAR_TOKEN: JoPoYk2g06FIZLsR+uuvRINFWdMJRgNQCM0LsTTigcDhJuw2USe9Y09WqyIgcWeKiR+j92Y0BI4a1Rm4uJARcYeNQOElgGKy2/Hu9Grx+3JsCZ+/JTYDjSG7+OV9QjhftA6mZ+kBcVf3ZgZf4bD6C5+RUY854i+TZzqM98iy1rYg+hxEwkThR+1R7hnk+rQWj3r9L2yjb2+F+AEBgm4bRbKoChoB6GUTsvpsV58KnSzNq4zqivhFzGZruFYF63wwCDmQB/nh0zjQaoOzhL7HrIeDRRNWgQUSz04MW1jxzkHZNDUQfA0LazGiGFtQYyjm/Gu2o5E8l2kUWHnKtANEy2XQHIQYsgmDsm4jMPwmEClAVfnMfB4QJcn0cXmNAskfbvv8DGQZBYxFFNuzpfsC9AogRunrLR34qR06gDvZS1Z5lo5ygbxwi5VJQLpPhJGJsrZFgUWhhwhQwcWcWH4eEZO3RmG8rC418V8iyn4TQl3AlElVkreJ6kPVi1VtlC1A3OVxNZmjWUbB9afCsXt9i25SCtlYZgMoz8l8KWzGkk6rvBj4NDEeggxWl/s6nisVckPRZK/6NgVPpk01Yq2PmG2hg9sbKO9e2byzII57q8Q0iGUfC/zeMLwf3mev/+F4s2ksj2Yc5771QUCpEppJXXPCC/naCyjS4f9Yo+xZYGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
