conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
bot:
  automerge: true
github:
  branch_name: main
  tooling_branch_name: main
conda_install_tool: pixi
conda_build_tool: rattler-build
conda_build:
  pkg_format: '2'
